# This workflow runs on commit to build a package which can be
# installed with Helios 1.6.  If the commit contains the text
# #patch then the patch level will be bumped.

name: CreateHelios16

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master, dev, test ]
  pull_request:
    branches: [ main, master, dev, test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VEHICLE: AH-64D_BLK_II
  VEHICLECOMMONNAME: AH-64D Apache
  MINHELIOSRELEASE: 1.6.5305.0001
  PROFILENAME: Apache

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "github.ref = ${{github.ref}}"
          if [ ${{ github.ref }} == "refs/heads/dev" ]; then
            echo "::set-output name=HELIOSBUILDTYPE::Dev"
            echo "::set-output name=HELIOSDIRECTORYNAME::Dev"
          elif [ ${{ github.ref }} == "refs/heads/test" ]; then
            echo "::set-output name=HELIOSBUILDTYPE::Test"
            echo "::set-output name=HELIOSDIRECTORYNAME::"
          else
            echo "::set-output name=HELIOSBUILDTYPE::"
            echo "::set-output name=HELIOSDIRECTORYNAME::"
          fi
      - name: Bump version and push 
        id: bump_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNERREPO_OWNER: BlueFinBima
          DEFAULT_BUMP: 'patch'
          INITIAL_VERSION: '0.0.0'
      - name: Check outputs
        run: |
          #env
          echo ${{ env.VEHICLE }} - ${{ env.VEHICLECOMMONNAME }}
          echo "Commit SHA (short) - " ${{ steps.vars.outputs.sha_short }}
          echo "New Release - V " ${{ steps.bump_tag.outputs.tag }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install diff-match-patch
          python -m pip install defusedxml
      - name: execute py script to install patches
        run: |
          python .github/workflows/AdjustLocalIrisConfig.py '${{ env.VEHICLE }}/Helios/Iris/${{ env.VEHICLE }}/${{ env.PROFILENAME }}_Local.iris' '${{ env.VEHICLE }}/Helios/Iris/${{ env.VEHICLE }}/${{ env.PROFILENAME }}_Pilot_Local.iris'  '${{ env.VEHICLE }}/Helios/Iris/${{ env.VEHICLE }}/${{ env.PROFILENAME }}_CPG_Local.iris' 1920 0 -1920 0
          python .github/workflows/apply_patch.py '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}.hpf' ".github/workflows/${{ env.PROFILENAME }}.hpf.gpatch" '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'
          sed -i -- 's#\.iris#_Local\.iris#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'            
          sed -i -- 's#<EmbeddedViewportName>.*</EmbeddedViewportName>#<EmbeddedViewportName />#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'            
          sed -i -- 's#Monitor 1#Monitor 2#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'            
      - name: Text Substitutions ( All Branches )
        run: |
          mkdir -p output
          echo Substituting general info in the Profile16.json manifest and the profile
          sed -i -- 's/_ReleaseDate/'"$(date "+%d %B %Y")"'/g' Profile16.json
          sed -i -- 's/_ReleaseDate/'"$(date "+%d %B %Y")"'/g' Profile16.json
          sed -i -- 's/_ProfileVersionNumber/'"V${{ steps.bump_tag.outputs.tag }}"'/g' Profile16.json
          sed -i -- 's/_Vehicle/'"${{ env.VEHICLE }}"'/g' Profile16.json
          sed -i -- 's#_Repository#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases"'#g' Profile16.json
          sed -i -- 's#_Author#'"${GITHUB_ACTOR}"'#g' Profile16.json
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLECOMMONNAME }} - About this profile.md'
          sed -i -- 's#_ProjectURL#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"'#g' '${{ env.VEHICLECOMMONNAME }} - About this profile.md'
          sed -i -- 's#_Repository#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases"'#g' '${{ env.VEHICLECOMMONNAME }} - About this profile.md'
          sed -i -- 's#_commit#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"'#g' '${{ env.VEHICLECOMMONNAME }} - About this profile.md'
          fnStub=$(echo ${{ env.VEHICLE }}/Helios/Iris/${{ env.VEHICLE }}/$GITHUB_ACTOR/${{ env.PROFILENAME }})
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}.iris
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}_Pilot.iris
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}_CPG.iris
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}_Local.iris
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}_Pilot_Local.iris
          sed -i -- 's#<Host>lightning.home</Host>#<Host>localhost</Host>#g' ${fnStub}_CPG_Local.iris

      - name: Text Substitutions ( Prod / Test)
        if: github.ref != 'refs/heads/dev'     
        run: |
          echo Substituting prod build info in the Profile16.json manifest
          sed -i -- 's/_MinimumReleaseLevel/${{ env.MINHELIOSRELEASE }}/g' Profile16.json
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}.hpf'
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'
          sed -i -- 's#_CockpitType#DUAL#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}.hpf'
          sed -i -- 's#_CockpitType#DUAL#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_CPG.hpf'
          sed -i -- 's#_CockpitType#CO-PILOT / GUNNER#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_CPG.hpf'
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Pilot.hpf'
          sed -i -- 's#_CockpitType#PILOT#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Pilot.hpf'
      - name: Text Substitutions ( Dev )
        if: github.ref == 'refs/heads/dev'
        run: |
          echo Substituting dev build info in the Profile16.json manifest
          sed -i -- 's/_MinimumReleaseLevel/1.6.1000.0000/g' Profile16.json
          sed -i -- 's#Helios/#HeliosDev/#g' Profile16.json
          smallTag=$(echo ${{ steps.bump_tag.outputs.tag }} | cut -c1-5)
          echo 'DEV '$smallTag
          sed -i -- 's#_ProfileVersionNumber#DEV '$smallTag'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}.hpf'
          sed -i -- 's#\\Helios\\Iris\\#\\HeliosDev\\Iris\\#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}.hpf'
          sed -i -- 's#_ProfileVersionNumber#DEV '$smallTag'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'
          sed -i -- 's#\\Helios\\Iris\\#\\HeliosDev\\Iris\\#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Local.hpf'
          sed -i -- 's#_ProfileVersionNumber#DEV '$smallTag'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_CPG.hpf'
          sed -i -- 's#\\Helios\\Iris\\#\\HeliosDev\\Iris\\#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Pilot.hpf'
          sed -i -- 's#_ProfileVersionNumber#DEV '$smallTag'#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_CPG.hpf'
          sed -i -- 's#\\Helios\\Iris\\#\\HeliosDev\\Iris\\#g' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }}_Pilot.hpf'
      - name: Rename Directory for development
        if: github.ref == 'refs/heads/dev'     
        run: mv ./${{ env.VEHICLE }}/Helios ./${{ env.VEHICLE }}/Helios${{ steps.vars.outputs.HELIOSDIRECTORYNAME }}
      # create a zip file using the runners shell
      - name: Package Files Prod
        run: zip -r "output/${{ env.VEHICLE }} ${{ steps.vars.outputs.HELIOSBUILDTYPE }}_V${{ steps.bump_tag.outputs.tag }}.helios16" ./Profile16.json ./LICENSE ./*.md ./${{ env.VEHICLE }}/Helios${{ steps.vars.outputs.HELIOSDIRECTORYNAME }}/ -x ".git/*" ".github/*" "./${{ env.VEHICLE }}/Helios${{ steps.vars.outputs.HELIOSDIRECTORYNAME }}/Profiles/*.bak" "./${{ env.VEHICLE }}/Helios${{ steps.vars.outputs.HELIOSDIRECTORYNAME }}/Profiles/*.hply"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VEHICLECOMMONNAME }} helios16 ${{ steps.vars.outputs.HELIOSBUILDTYPE }} package
          path: output/${{ env.VEHICLE }} ${{ steps.vars.outputs.HELIOSBUILDTYPE }}_V${{ steps.bump_tag.outputs.tag }}.helios16
          retention-days: 2
