name: Remove old artifacts

on:
  workflow_dispatch:
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '60 seconds' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5